# schemas.py
# Pydantic models that define the shape of HTTP request and response bodies.
#
# PlayerRequest  — what the client sends to POST /analyze-player (inputs only)
# PlayerResponse — what the server sends back (outputs only)
#
# Why two separate models?
#   The request holds what the user provides.
#   The response holds what the workflow produces.
#   Mixing them in one model is confusing and breaks API documentation.

from pydantic import BaseModel, Field, model_validator
from typing import Annotated


class PlayerRequest(BaseModel):
    # ── Batting inputs (balls=0 means player did not bat) ─────────────────────
    runs   : Annotated[int,   Field(..., ge=0, description="Total runs scored")]
    balls  : Annotated[int,   Field(..., ge=0, description="Balls faced (0 if player did not bat)")]
    fours  : Annotated[int,   Field(..., ge=0, description="Number of fours hit")]
    sixes  : Annotated[int,   Field(..., ge=0, description="Number of sixes hit")]

    # ── Bowling inputs (overs=0 means player did not bowl) ────────────────────
    overs         : Annotated[float, Field(..., ge=0, description="Overs bowled (0 if player did not bowl)")]
    runs_conceded : Annotated[int,   Field(..., ge=0, description="Runs given away while bowling")]
    wickets       : Annotated[int,   Field(..., ge=0, description="Wickets taken")]

    @model_validator(mode='after')
    def at_least_one_discipline(self) -> 'PlayerRequest':
        """Reject requests where the player neither batted nor bowled."""
        if self.balls == 0 and self.overs == 0:
            raise ValueError('At least one discipline must be filled: balls > 0 (batting) or overs > 0 (bowling).')
        return self


class PlayerResponse(BaseModel):
    # ── Computed metrics (from parallel nodes) ────────────────────────────────
    batting_metrics : dict    # strike rate, boundary ratio, dot ball %
    bowling_metrics : dict    # economy rate, bowling average, bowling strike rate

    # ── Fusion outputs ────────────────────────────────────────────────────────
    impact_score : float      # Combined performance score (0-100)
    player_role  : str        # e.g. "power_hitter", "economy_controller"

    # ── AI scouting summary ───────────────────────────────────────────────────
    final_report : str        # Generated by insight_generator_node
